name: CI
on:
    pull_request:
        branches: [develop]
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
            SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        steps:
            - uses: actions/checkout@v2
            - name: Use NodeJs
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: |
                  npm ci
                  npm run format:check
                  npm test -- --coverage
              env:
                  CI: true
            - name: Build Project
              if: github.event_name == 'push'
              run: |
                  npm install -g surge
                  npm build
            - name: Deploy to Stage
              if: github.event_name == 'push'
              run: surge --project ./build --domain purring-meal.surge.sh --token ${{ secrets.SURGE_TOKEN }}
